//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FieldGateway.Telemetry.Generator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FieldGateway.Telemetry.Generator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2016-07-19T22:07:24.859Z,40.276905,118.969146,1999.99,644.138486312399,400.01,179.99,1,5,20.01,50.02,990.31,2012.99,1.11,0.21,0.31,180.33,0.86,90.77,12.11,7.39,1233
        ///2016-07-19T22:07:25.359Z,40.276905,118.969156,1999.98,644.154589371981,400.02,179.98,1,6,20.02,50.04,990.28,2012.98,1.12,0.22,0.32,180.32,0.87,90.78,12.12,7.38,1232
        ///2016-07-19T22:07:25.859Z,40.276905,118.969166,1999.97,644.170692431562,400.03,179.97,1,7,20.03,50.06,990.25,2012.97,1.13,0.23,0.33,180.31,0.88,90.79,12.13,7.37,1231
        ///2016-07-19T22: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RT_Telemetry_Test {
            get {
                return ResourceManager.GetString("RT_Telemetry_Test", resourceCulture);
            }
        }
    }
}
